stages:
  - install
  - security

install_job:
  stage: install
  tags:
    - sobarqube
  image: node:22-alpine
  script:
    - cd end_to_end_devsecops_project
    - npm install

sonarqube_check:
  stage: security
  tags:
    - sobarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner
  variables:
    SONAR_TOKEN: $SONAR_TOKEN