stages:
  - test
  - security
  - build

variables:
  IMAGE_NAME: "$dockerhub_username/end-to-end-devsecops-project:$CI_PIPELINE_IID"

unit_test:
  stage: test
  tags:
    - sobarqube
  image: node:20-alpine
  script:
    - cd end_to_end_devsecops_project
    - npm test

sonarqube_check:
  stage: security
  tags:
    - sobarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - echo "Testing SonarQube token"
    - sonar-scanner -Dsonar.token=$SONAR_TOKEN

build_and_push_image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:26-dind

  before_script:
    - echo "Username length: ${#dockerhub_username}"
    - echo "Token length: ${#dockerhub_token}"
    - echo "$dockerhub_token" | docker login -u "$dockerhub_username" --password-stdin

  script:
    - cd end_to_end_devsecops_project
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
    - docker images

  needs:
    - sonarqube_check