stages:
  - test
  - quality
  - build
  - security
  - deploy

variables:
  IMAGE_NAME: "$dockerhub_username/end-to-end-devsecops-project:$CI_PIPELINE_IID"

unit_test:
  stage: test
  tags:
    - sobarqube
  image: node:20-alpine
  script:
    - cd end_to_end_devsecops_project
    - npm install
    - npm test

sonarqube_check:
  stage: quality
  tags:
    - sobarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - echo "Testing SonarQube token"
    - sonar-scanner -Dsonar.token=$SONAR_TOKEN

build_and_push_image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:26-dind

  before_script:
    - echo "Docker username length ${#dockerhub_username}"
    - echo "Docker token length ${#dockerhub_token}"
    - echo "$dockerhub_token" | docker login -u "$dockerhub_username" --password-stdin

  script:
    - cd end_to_end_devsecops_project
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
    - docker images

  needs:
    - sonarqube_check


trivy_scan_image:

  stage: security
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image  --severity CRITICAL "$IMAGE_NAME"
  needs: 
    - build_and_push_image

deploy_to_eks:
  stage: deploy

  image:
    name: alpine/k8s:1.35.0
    entrypoint: [""]

  environment:
    name: production

  before_script:
    - aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$AWS_REGION"

  script:
    
    - sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_NAME|g" end_to_end_devsecops_project/K8s/app/deployment.yaml
    - kubectl apply -f end_to_end_devsecops_project/K8s/app/
    - kubectl apply -f end_to_end_devsecops_project/K8s/monitoring/prometheus-rule.yaml
    - kubectl apply -f end_to_end_devsecops_project/K8s/monitoring/alertmanager-config.yaml
    - kubectl -n devops-project rollout status deployment/end-to-end-devops-project

  needs:
    - trivy_scan_image