prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false


grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer

alertmanager:
  enabled: true
  alertmanagerSpec:
    alertmanagerConfigNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - devops-project
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: devops-project-email
